server:
  port: 8080
  servlet:
    context-path: /gdgoc_dashboard

spring:
  application:
    name: gdgoc-dashboard

  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc_dashboard
    username: postgres
    password: sbien13112002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

firebase:
  service-account-path: firebase-service-account.json
